// Lista de textos
const texts = [
  " Você é importante, nunca se esqueça disso.",
  " Sua vida vale muito, cuide de você.",
  " Há sempre um novo amanhecer, confie no processo.",
  " Acredite no seu valor, o mundo precisa de você.",
  " Não tenha medo de pedir ajuda, você não está sozinho.",
  " A sua presença faz a diferença.",
  " Você é mais forte do que imagina.",
  " Cada passo que você dá é um avanço importante.",
  " O amanhã traz novas oportunidades.",
  " Você é único, e isso é sua força.",
  " O primeiro passo para a mudança é acreditar.",
  " Seus sentimentos importam, valorize-os.",
  " Você merece ser feliz, nunca duvide disso.",
  " Compartilhar suas lutas faz você mais forte.",
  " Ser gentil consigo mesmo é um ato de coragem.",
  " Cada dificuldade é uma chance de crescer.",
  " O seu sorriso ilumina o mundo ao seu redor.",
  " Não desista, seu melhor ainda está por vir.",
  " Você não está sozinho nesta jornada.",
  " Tudo pode mudar, acredite em dias melhores.",
  " Você é mais amado do que imagina.",
  " Você é um tesouro para quem te ama.",
  " Pequenas vitórias merecem ser celebradas.",
  " Todo dia é uma nova chance para recomeçar.",
  " A ajuda está sempre mais próxima do que parece.",
  " Você tem o poder de transformar sua história.",
  " Sua existência faz o mundo mais bonito.",
  " Você é mais forte que qualquer tempestade.",
  " Você importa, sempre.",
  " O amor-próprio é o primeiro passo para a cura.",
  " A vida é feita de altos e baixos, continue firme.",
  " Seu valor não é medido pelas suas dificuldades.",
  " Você é capaz de superar qualquer desafio.",
  " Um dia de cada vez, e você chegará lá.",
  " Tudo tem um jeito, basta pedir ajuda.",
  " A vida é preciosa e única, assim como você.",
  " Você é digno de amor e carinho.",
  " Nunca subestime a força que existe em você.",
  " Lembre-se: o seu bem-estar vem em primeiro lugar.",
  " Momentos difíceis não duram para sempre.",
  " Sua saúde mental é prioridade, cuide dela.",
  " Respire fundo, você vai superar isso.",
  " Mesmo nas nuvens mais escuras, o sol brilha por trás.",
  " Você é muito mais que seus momentos de tristeza.",
  " O amanhã é sempre uma nova oportunidade.",
  " Sua voz merece ser ouvida.",
  " A vida é um presente, valorize cada instante.",
  " Ser vulnerável é ser corajoso.",
  " Todo desafio traz consigo uma lição.",
  " Você merece se sentir bem.",
  " Não se apresse, cada coisa tem seu tempo.",
  " Cuidar de si é um ato de amor.",
  " Não tenha vergonha de pedir ajuda.",
  " A sua felicidade é possível e necessária.",
  " Permita-se ser feliz, mesmo nos dias difíceis.",
  " Você não está sozinho em seus sentimentos.",
  " Sua vida é única e merece ser vivida plenamente.",
  " Grandes coisas começam com pequenos passos.",
  " O cuidado com a mente é tão importante quanto com o corpo.",
  " A ajuda é um ato de coragem, não de fraqueza.",
  " Não se isole, há sempre alguém disposto a escutar.",
  " Seu bem-estar emocional é essencial.",
  " Momentos difíceis também passam.",
  " Não tenha medo de falar sobre seus sentimentos.",
  " Cada dia é uma nova chance para recomeçar.",
  " Você é digno de felicidade.",
  " Sua força interior é maior do que imagina.",
  " Há beleza na sua luta e na sua história.",
  " O mundo precisa da sua luz, não desista.",
  " Cada amanhecer traz uma nova chance.",
  " Seu futuro é cheio de possibilidades.",
  " Não deixe a tristeza definir quem você é.",
  " Você não precisa enfrentar tudo sozinho.",
  " Peça ajuda, sua vida é valiosa.",
  " Você é amado por ser quem é.",
  " Seus sentimentos são válidos e importantes.",
  " A cura começa com o primeiro passo.",
  " Acredite em você, o mundo precisa de sua força.",
  " Você é importante demais para desistir.",
  " Você pode encontrar paz, mesmo em meio ao caos.",
  " Há sempre esperança, mesmo nos dias difíceis.",
  " A vida é feita de recomeços.",
  " Cuide de sua saúde mental com carinho.",
  " Não tenha medo de ser quem você é.",
  " Cada pequena vitória é motivo de celebração.",
  " Você é suficiente exatamente como é.",
  " Sua vida é uma jornada única e especial.",
  " Aceite-se como é, isso é um ato de amor.",
  " Dias ruins não duram para sempre.",
  " Sua história importa e inspira outros.",
  " Você não precisa enfrentar tudo de uma vez.",
  " Dê a si permissão para descansar.",
  " Sua vida é um presente precioso.",
  " A esperança sempre floresce em seu tempo.",
  " Tudo ficará bem, acredite.",
  " Você é forte, mesmo quando se sente fraco.",
  " Há sempre alguém disposto a te ouvir.",
  " Você merece encontrar paz e felicidade.",
  " Lembre-se: pedir ajuda é um sinal de força."
];

// Função para selecionar um texto aleatório
function getRandomText() {
  const randomIndex = Math.floor(Math.random() * texts.length);
  return texts[randomIndex];
}

// Exibir o texto na página
document.addEventListener("DOMContentLoaded", () => {
  const textElement = document.getElementById("random-text");
  textElement.textContent = getRandomText();
});
